cp -v $HOME/majstaf/coding2/testing/zig_testing/zt_005_cli-args-tests_20250317/clean.sh $HOME/majstaf/coding2/testing/ALLSCR/zt_005_clean.sh
cp -v $HOME/majstaf/coding2/testing/zig_testing/zt_SCRIPTS/zig-clean.sh $HOME/majstaf/coding2/testing/ALLSCR/zt_SCR_zig-clean.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_060_fizzbuzz_20220826/fizzbuzz.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_060_fizzbuuzz.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_OSTALO/img2term/build.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_OST_img2term_build.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_OSTALO/check-gcc-standard/test-gcc-std.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_OST_check-gcc-standard_test-gcc-std.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_OSTALO/c_rotating-cube_20220901/build.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_OST_c_rotating-cube_20220901_build.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_OSTALO/horse-race/build-and-run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_OST_horse-race_build-and-run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_OSTALO/horse-race/run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_OST_horse-race_run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_OSTALO/c_compile_clean_target_scripts_demo_2025012/clean_target $HOME/majstaf/coding2/testing/ALLSCR/ct_OST_c_compile_clean_target_scripts_demo_2025012_clean_target
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_OSTALO/c_compile_clean_target_scripts_demo_2025012/compile $HOME/majstaf/coding2/testing/ALLSCR/ct_OST_c_compile_clean_target_scripts_demo_2025012_compile
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_086_is_prime_20221208/test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_086_test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_098_reversed_20230412/build_and_run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_098_build_and_run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_098_reversed_20230412/build.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_098_build.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_049_PI2_20220315/test/PI-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_049_test_PI-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_003_c-pointers-testing_20210929/staro_make_scripts/make_linuxexecutable.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_003_staro_make_scripts_make_linuxexecutable.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_003_c-pointers-testing_20210929/staro_make_scripts/make_winexecutable.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_003_staro_make_scripts_make_winexecutable.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_003_c-pointers-testing_20210929/staro/make_linuxexecutable.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_003_staro_make_linuxexecutable.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_003_c-pointers-testing_20210929/staro/make_winexecutable.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_003_staro_make_winexecutable.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_109_relative_pointers_btree_20230825/test/build.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_109_test_build.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_109_relative_pointers_btree_20230825/test/clear_binaries.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_109_test_clear_binaries.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_109_relative_pointers_btree_20230825/test/Build_and_Run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_109_test_Build_and_Run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_109_relative_pointers_btree_20230825/build.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_109_build.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_109_relative_pointers_btree_20230825/clear_binaries.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_109_clear_binaries.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_109_relative_pointers_btree_20230825/Build_and_Run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_109_Build_and_Run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_METSYS/return-null-missing_20211101.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_MET_return-null-missing_20211101.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_054_memory-management-testing_20220524/testing/mvalgrind-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_054_testing_mvalgrind-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_054_memory-management-testing_20220524/mvalgrind-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_054_mvalgrind-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_054_memory-management-testing_20220524/valgrind-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_054_valgrind-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_007_dirs-test_20211008/check_length.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_007_check_length.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_088_BrthReminder-02_20221222/valgrind-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_088_valgrind-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_097_vector_la_from_pascal_20230406/clean_bin.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_097_clean_bin.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/rename_build_to_bin_20250202.sh $HOME/majstaf/coding2/testing/ALLSCR/rename_build_to_bin_20250202.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/rename_bin_to_build_20241203.sh $HOME/majstaf/coding2/testing/ALLSCR/rename_bin_to_build_20241203.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_053_BrthReminder_20220416/valgrind-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_053_valgrind-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_127_BrthReminder-03_20240312/valgrind-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_127_valgrind-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_072_linked-list-test_20221016/mvalgrind-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_072_mvalgrind-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_095_test_returning_pointer_to_struct_from_function_20230328/valgrind-test.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_095_valgrind-test.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_108_region-allocator-test_20230821/generate_100MB_random_txt_file.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_108_generate_100MB_random_txt_file.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_077_graph-with-adjacency-matrix_20221028/build.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_077_build.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_118_path_construction_macro_20231113/_build_and_run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_118__build_and_run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_107_struct-serialization_20230607/compile_and_run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_107_compile_and_run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_129_path_construction_macro_2_20240524/create_test_dir_with_files.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_129_create_test_dir_with_files.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_129_path_construction_macro_2_20240524/build_and_run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_129_build_and_run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_129_path_construction_macro_2_20240524/create_test_TRII_structure.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_129_create_test_TRII_structure.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_126_substring_with_pointers_20240312/build_and_run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_126_build_and_run.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_081_voronoi_graph_20221123/_build-and-run_d.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_081__build-and-run_d.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_081_voronoi_graph_20221123/build.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_081_build.sh
cp -v $HOME/majstaf/coding2/testing/c_testing/ct_081_voronoi_graph_20221123/_build-and-run.sh $HOME/majstaf/coding2/testing/ALLSCR/ct_081__build-and-run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_068_jpms-01_20200417/com.example.gui2/run2.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_068_com.example.gui2_run2.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_042_create_softlink_run_shell_command_20190204/CreateSoftlink_jar_wrapper.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_042_CreateSoftlink_jar_wrapper.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_042_create_softlink_run_shell_command_20190204/CreateSoftlink_java_wrapper.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_042_CreateSoftlink_java_wrapper.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_069_jvfx_registration-form_20200420/jxc $HOME/majstaf/coding2/testing/ALLSCR/jt_069_jxc
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_069_jvfx_registration-form_20200420/from-net/jxc $HOME/majstaf/coding2/testing/ALLSCR/jt_069_from-net_jxc
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_069_jvfx_registration-form_20200420/from-net/jxr $HOME/majstaf/coding2/testing/ALLSCR/jt_069_from-net_jxr
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_069_jvfx_registration-form_20200420/jxr $HOME/majstaf/coding2/testing/ALLSCR/jt_069_jxr
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_057_CountryCapitalsGui_jsnon_20200422/CountriesCapitalsGUI3.run $HOME/majstaf/coding2/testing/ALLSCR/jt_057_CountriesCapitalsGUI3.run
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_057_CountryCapitalsGui_jsnon_20200422/CountriesCapitalsGUI3-1.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_057_CountriesCapitalsGUI3-1.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_bankovci-kovanci_20200904/BankovciInKovanci.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_070_BankovciInKovanci.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_bankovci-kovanci_20200904/run-class.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_070_run-class.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_bankovci-kovanci_20200904/compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_070_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_bankovci-kovanci_20200904/makejar.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_070_makejar.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_084_sortedArray-and-sorrtedTreeSet_20200821/compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_084_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_084_sortedArray-and-sorrtedTreeSet_20200821/run.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_084_run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_088_combinatorics_20200901/RunCombinations2.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_088_RunCombinations2.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_088_combinatorics_20200901/RunCombinatorics.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_088_RunCombinatorics.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_065_sortedArray-and-sorrtedTreeSet_20200821/run-d.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_065_run-d.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_065_sortedArray-and-sorrtedTreeSet_20200821/compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_065_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_032_elektrika_en_20181120/elektrika_d.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_032_elektrika_d.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_032_elektrika_en_20181120/elektrika.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_032_elektrika.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_050_regex_files_20200320/RsortByEnddate_run.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_050_RsortByEnddate_run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_080_jars-with-external-jars-test_20200806/deploy/MainAppWithCustomJre/run.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_080_deploy_MainAppWithCustomJre_run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_062_jars-with-external-jars-test_20200806/application-modular/jars1/run1.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_062_application-modular_jars1_run1.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_062_jars-with-external-jars-test_20200806/application-modular/jars2/run2.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_062_application-modular_jars2_run2.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_062_jars-with-external-jars-test_20200806/deploy/MainAppWithCustomJre/run_d.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_062_deploy_MainAppWithCustomJre_run_d.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_066_Country-json_20200404/jrun.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_066_jrun.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_052_jvfx_simple_20200403/create_aliases.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_052_create_aliases.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_052_jvfx_simple_20200403/jxc $HOME/majstaf/coding2/testing/ALLSCR/jt_052_jxc
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_052_jvfx_simple_20200403/jxr $HOME/majstaf/coding2/testing/ALLSCR/jt_052_jxr
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_089_bankovci-kovanci_20200904/BankovciInKovanci.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_089_BankovciInKovanci.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_089_bankovci-kovanci_20200904/run-class.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_089_run-class.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_089_bankovci-kovanci_20200904/compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_089_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_089_bankovci-kovanci_20200904/makejar.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_089_makejar.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_068_ListTest-with-scripts_20200825/makedoc.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_068_makedoc.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_068_ListTest-with-scripts_20200825/compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_068_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_068_ListTest-with-scripts_20200825/run.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_068_run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_056_pdtk_gui_20200420/scripts/UIControls.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_056_scripts_UIControls.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_056_pdtk_gui_20200420/scripts/jxc $HOME/majstaf/coding2/testing/ALLSCR/jt_056_scripts_jxc
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_056_pdtk_gui_20200420/scripts/jxr $HOME/majstaf/coding2/testing/ALLSCR/jt_056_scripts_jxr
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_056_pdtk_gui_20200420/V2/scripts/UIControls.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_056_V2_scripts_UIControls.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_056_pdtk_gui_20200420/V2/scripts/jxc $HOME/majstaf/coding2/testing/ALLSCR/jt_056_V2_scripts_jxc
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_056_pdtk_gui_20200420/V2/scripts/jxr $HOME/majstaf/coding2/testing/ALLSCR/jt_056_V2_scripts_jxr
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_069_combinatorics_20200901/RunCombinations2.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_069_RunCombinations2.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_069_combinatorics_20200901/RunCombinatorics.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_069_RunCombinatorics.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_OSTALO/javaFX_tests/jvfx_compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_OST_javaFX_tests_jvfx_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_OSTALO/javaFX_tests/jvfx_run.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_OST_javaFX_tests_jvfx_run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_OSTALO/RENAME_20191025.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_OST_RENAME_20191025.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_071_dependency-injections_20200911/run-all.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_071_run-all.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_071_dependency-injections_20200911/depinjections_compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_071_depinjections_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_090_dependency-injections_20200911/run-all.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_090_run-all.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_090_dependency-injections_20200911/depinjections_compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_090_depinjections_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_pdtk_gui_20200420/scripts/UIControls.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_070_scripts_UIControls.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_pdtk_gui_20200420/scripts/jxc $HOME/majstaf/coding2/testing/ALLSCR/jt_070_scripts_jxc
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_pdtk_gui_20200420/scripts/jxr $HOME/majstaf/coding2/testing/ALLSCR/jt_070_scripts_jxr
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_pdtk_gui_20200420/V2/scripts/UIControls.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_070_V2_scripts_UIControls.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_pdtk_gui_20200420/V2/scripts/jxc $HOME/majstaf/coding2/testing/ALLSCR/jt_070_V2_scripts_jxc
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_070_pdtk_gui_20200420/V2/scripts/jxr $HOME/majstaf/coding2/testing/ALLSCR/jt_070_V2_scripts_jxr
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_065_jvfx_simple_20200403/create_aliases.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_065_create_aliases.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_065_jvfx_simple_20200403/jxc $HOME/majstaf/coding2/testing/ALLSCR/jt_065_jxc
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_065_jvfx_simple_20200403/jxr $HOME/majstaf/coding2/testing/ALLSCR/jt_065_jxr
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_077_rsort-by-datestamp_20220129/RsortByEnddate_run $HOME/majstaf/coding2/testing/ALLSCR/jt_077_RsortByEnddate_run
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_077_rsort-by-datestamp_20220129/RsortByEnddate_run.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_077_RsortByEnddate_run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_086_ListTest-with-scripts_20200825/makedoc.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_086_makedoc.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_086_ListTest-with-scripts_20200825/compile.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_086_compile.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_086_ListTest-with-scripts_20200825/run.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_086_run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_100_rsort-by-datestamp_20220129/RsortByEnddate_run $HOME/majstaf/coding2/testing/ALLSCR/jt_100_RsortByEnddate_run
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_100_rsort-by-datestamp_20220129/RsortByEnddate_run.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_100_RsortByEnddate_run.sh
cp -v $HOME/majstaf/coding2/testing/java_testing/jt_100_rsort-by-datestamp_20220129/RsortByEnddate_run2.sh $HOME/majstaf/coding2/testing/ALLSCR/jt_100_RsortByEnddate_run2.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_095_kivy-test/RUN.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_095_RUN.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_SCRIPTS/venv_jupiter_notebook_scripts/run_jn.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_SCR_venv_jupiter_notebook_scripts_run_jn.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_SCRIPTS/venv_jupiter_notebook_scripts/build.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_SCR_venv_jupiter_notebook_scripts_build.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_SCRIPTS/venv_jupiter_notebook_scripts/build_and_run_jn.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_SCR_venv_jupiter_notebook_scripts_build_and_run_jn.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_OSTALO/makevenv_d/venv_s2_pip_update_and_install_d.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_OST_makevenv_d_venv_s2_pip_update_and_install_d.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_OSTALO/makevenv_d/venv_s3_remove_venv.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_OST_makevenv_d_venv_s3_remove_venv.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_OSTALO/makevenv_d/venv_s1_makevenv_d.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_OST_makevenv_d_venv_s1_makevenv_d.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_OSTALO/RENAME-20191025.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_OST_RENAME-20191025.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_OSTALO/makevenv_en/venv_s2_pip_update_and_install_en_b $HOME/majstaf/coding2/testing/ALLSCR/pt_OST_makevenv_en_venv_s2_pip_update_and_install_en_b
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_OSTALO/makevenv_en/venv_s1_makevenv_en_b $HOME/majstaf/coding2/testing/ALLSCR/pt_OST_makevenv_en_venv_s1_makevenv_en_b
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_OSTALO/makevenv_en/venv_s3_remove_venv.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_OST_makevenv_en_venv_s3_remove_venv.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_OSTALO/RENAME_20191025.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_OST_RENAME_20191025.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_083_PI2_20211220/test/PI-test.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_083_test_PI-test.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_082_folium_test_20230818/run_jn.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_082_run_jn.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_082_folium_test_20230818/build.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_082_build.sh
cp -v $HOME/majstaf/coding2/testing/python_testing/pt_082_folium_test_20230818/build_and_run_jn.sh $HOME/majstaf/coding2/testing/ALLSCR/pt_082_build_and_run_jn.sh
cp -v $HOME/majstaf/coding2/testing/rust_testing/rst_SCRIPTS/rst_compile_and_run.sh $HOME/majstaf/coding2/testing/ALLSCR/rst_SC_rst_compile_and_run.sh
cp -v $HOME/majstaf/coding2/testing/rust_testing/rst_OSTALO/rustexamples/test_20230609/rst_compile_and_run.sh $HOME/majstaf/coding2/testing/ALLSCR/rst_OS_rst_compile_and_run.sh
cp -v $HOME/majstaf/coding2/testing/rust_testing/rst_RUST_BOOK_PROJECTS/structs/build_and_run_struct_test_print.sh $HOME/majstaf/coding2/testing/ALLSCR/rst_RU_build_and_run_struct_test_print.sh
cp -v $HOME/majstaf/coding2/testing/ncurses_testing/nct_004_guessing_game_test_20250123/clean_target $HOME/majstaf/coding2/testing/ALLSCR/nct_004_clean_target
cp -v $HOME/majstaf/coding2/testing/ncurses_testing/nct_004_guessing_game_test_20250123/compile $HOME/majstaf/coding2/testing/ALLSCR/nct_004_compile
cp -v $HOME/majstaf/coding2/testing/ncurses_testing/nct_003_window-colors-testing_20240412/tools/all_over_again.sh $HOME/majstaf/coding2/testing/ALLSCR/nct_003_all_over_again.sh
cp -v $HOME/majstaf/coding2/testing/ncurses_testing/nct_003_window-colors-testing_20240412/tools/_build_and_run.sh $HOME/majstaf/coding2/testing/ALLSCR/nct_003__build_and_run.sh
cp -v $HOME/majstaf/coding2/testing/ncurses_testing/nct_003_window-colors-testing_20240412/tools/build.sh $HOME/majstaf/coding2/testing/ALLSCR/nct_003_build.sh
cp -v $HOME/majstaf/coding2/testing/ncurses_testing/nct_003_window-colors-testing_20240412/tools/clean.sh $HOME/majstaf/coding2/testing/ALLSCR/nct_003_clean.sh
cp -v $HOME/majstaf/coding2/testing/go_testing/gt_OSTALO/RENAME_20191025.sh $HOME/majstaf/coding2/testing/ALLSCR/gt_OST_RENAME_20191025.sh
cp -v $HOME/majstaf/coding2/testing/go_testing/gt_OSTALO/rename2_seznam2.sh $HOME/majstaf/coding2/testing/ALLSCR/gt_OST_rename2_seznam2.sh
